[versions]
agp = "8.5.2"
coil-compose = "2.7.0"
kotlin = "1.9.0"
core-ktx = "1.13.1"
appcompat = "1.7.0"
compose-bom = "2024.06.00"
navigation-compose = "2.7.7"
tv-foundation = "1.0.0-alpha11"
tv-material = "1.0.0-rc02"
lifecycle-runtime-ktx = "2.8.4"
activity-compose = "1.9.1"

[libraries]
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "tv-foundation" }
tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tv-material" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-ui = { group = 'androidx.compose.ui', name = 'ui', version = "1.7.0-beta07" }
compose-foundation = { group = 'androidx.compose.foundation', name = 'foundation', version = "1.7.0-beta07" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
