[versions]
agp = "8.2.2"
kotlin = "1.9.0"
core-ktx = "1.12.0"
appcompat = "1.6.1"
compose-bom = "2023.08.00"
tv-foundation = "1.0.0-alpha10"
tv-material = "1.0.0-alpha10"
lifecycle-runtime-ktx = "2.7.0"
activity-compose = "1.8.2"
hilt-navigation-compose = "1.1.0"
hilt-android = "2.48.1"
kotlin-android = "1.9.0"
kotlinx-serialization = "1.6.0"
ksp = "1.9.0-1.0.13"
kotlinx-coroutines = "1.6.0"
navigation-compose = "2.7.6"
core-splashscreen = "1.0.1"
benchmark-macro-junit4 = "1.2.2"
coil-compose = "2.5.0"
media3-ui = "1.3.0"
media3-exoplayer = "1.3.0"
constraint-layout = "1.0.1"
junit = "1.1.5"
espresso-core = "3.5.1"
uiautomator = "2.3.0"
profileinstaller = "1.3.1"
benchmark = "1.2.3"



[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-hilt-android = { module = "androidx.hilt:hilt-android", version.ref = "hilt-android" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "tv-foundation" }
tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tv-material" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3-ui" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraint-layout" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-android" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "benchmark" }


