[versions]
appcompat = "1.7.0"
cardview = "1.0.0"
converter-gson = "2.11.0"
dagger = "2.21"
espresso-core = "3.6.1"
glide = "4.15.1"
gson = "2.12.1"
junit = "4.13.2"
kotlin-android = "2.1.10"
android-gradle-plugin = "8.9.1"
leanback = "1.0.0"
legacy-preference-v14 = "1.0.0"
lifecycle-extensions = "2.2.0"
lifecycle-version = "2.8.7"
material = "1.12.0"
media3-exoplayer = "1.6.1"
palette-ktx = "1.0.0"
preference-ktx = "1.2.1"
recyclerview = "1.4.0"
room-runtime = "2.7.0"
runner = "1.6.1"
androidx-junit = "1.2.1"
tvprovider = "1.0.0"


[libraries]
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso-core" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle-version" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette-ktx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-rules = { module = "androidx.test:rules", version.ref = "runner" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-tvprovider = { module = "androidx.tvprovider:tvprovider", version.ref = "tvprovider" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

junit = { module = "junit:junit", version.ref = "junit" }
leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }
leanback-preference = { module = "androidx.leanback:leanback-preference", version.ref = "leanback" }
legacy-preference-v14 = { module = "androidx.legacy:legacy-preference-v14", version.ref = "legacy-preference-v14" }
material = { module = "com.google.android.material:material", version.ref = "material" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converter-gson" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }


[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-android" }